# Generated by Django 4.0.4 on 2022-06-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=200)),
                ('pagamento', models.CharField(choices=[('Cr', 'Crédito'), ('De', 'Débito'), ('Di', 'Dinheiro'), ('Cr', 'Criptomoeda')], max_length=20)),
                ('qntnovosprods', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Ca', 'Cancelado'), ('En', 'Entregue'), ('Ac', 'A caminho'), ('At', 'Atrasado'), ('En', 'Enviado')], max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produto')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.usuario')),
            ],
        ),
    ]
