# Generated by Django 4.0.4 on 2022-06-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Ca', 'Cancelado'), ('En', 'Entregue'), ('Ac', 'A caminho'), ('At', 'Atrasado'), ('Ev', 'Enviado')], max_length=20),
        ),
    ]
