# Generated by Django 4.0.4 on 2022-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Ac', 'A caminho'), ('Ev', 'Enviado'), ('En', 'Entregue'), ('At', 'Atrasado'), ('Ca', 'Cancelado')], max_length=20),
        ),
    ]
