# Generated by Django 4.0.4 on 2022-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('Cr', 'Crédito'), ('De', 'Débito'), ('Di', 'Dinheiro'), ('Cp', 'Criptomoeda')], max_length=20),
        ),
    ]
