# Generated by Django 4.0.4 on 2022-06-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('sistema', '0008_alter_produto_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedores.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedores.fornecedor'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
