# Generated by Django 4.0.4 on 2022-06-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('autenticacao', '0001_initial'),
        ('sistema', '0010_alter_pedido_filial_delete_filial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pag',
            new_name='pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produto'),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
