# Generated by Django 4.0.4 on 2022-06-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_rename_pag_pedido_pagamento_pedido_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
